### ISSUE TITLE
Does this package Support Laravel 5.1 or 5

### ISSUE THREAD

**Issue by hsvikum** [reportico-web/laravel-reportico#1]
I was trying to install this and got

Problem 1
    - Installation request for reportico/laravel-reportico dev-master -> satisfiable by reportico/laravel-reportico[dev-master].
    - Conclusion: remove laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.2
    - reportico/laravel-reportico dev-master requires illuminate/support 4.2.\* -> satisfiable by illuminate/support[4.2.x-dev, v4.2.0-BETA1, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support 4.2.x-dev|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.0-BETA1|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.1.2
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.1.2
    - Installation request for laravel/framework == 5.1.2.0 -> satisfiable by laravel/framework[v5.1.2].

Is there a workaround .Any Input would be helpful.

Thanks In advance

**Comment by reportico-web** [comment]
Hi there.... 

I havent tried to get this working with 5.x ... please give me a day or two to get this working .. i hope its only a case of updating dependencies. I'll post here when it is finished

Peter Deed

**Comment by hsvikum** [comment]
Thank you very much for the quick response. I'm looking forward to using this on an upcoming project .

**Comment by reportico-web** [comment]
Hi there I think I just got it working if you want to try the latest with following instructions:-

composer require "reportico/laravel-reportico" "~5.1"

then add to your app.php in the providers section :--

Reportico\Reportico\ReporticoServiceProvider::class

then publish the config and the assets with:-

php artisan vendor:publish

and point your browser at

http://laravel_url/public/index.php/reportico

To get going with the module go to :-

http://www.reportico.org/laravel/public/index.php

**Comment by hsvikum** [comment]
Thanks Peter Deed.I will close the issue.

**Comment by reportico-web** [comment]
Hi there, thanks for the feedback.. did it install and work for you?

**Comment by hsvikum** [comment]
Hi again it seems when i try to register as admin the ajax call doesn't pass through 

http://localhost/lara/laravel/public/index.php/reportico/ajax Failed to load resource: the server responded with a status of 500 (Internal Server Error) 

i checked the laravel log.this was the issue.

local.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /var/www/html/lara/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:53

i have given full permission to the whole laravel folder

**Comment by reportico-web** [comment]
ok i had this same error when i was getting this working and i realise the ajax call isnt getting through CSRF validation...

I think by commenting out
        //\App\Http\Middleware\VerifyCsrfToken::class,

in app/Http/Kernel.php it starts working .. but im now seeing if i can fix the problem properly

**Comment by reportico-web** [comment]
Ok I think i have a solution.

Looking at the laravel solutions i think the answer is to modify the session validation rules to exclude Reportico ajax requests because reportico must be pluggable into sites that have a variety of session token validation methods. So you should modify the file:-

```
app/Http/Middleware/VerifyCsrfToken.php
```

to add in to the except array :-

```
    protected $except = [
        //
        'reportico/*',
    ];
```

Please try this, I will check on the forum to see if there is a way i can control this from within the package but i suspect not.

Peter

**Comment by hsvikum** [comment]
Hi Peter,
This solution seems to work.Thanks.
