### ISSUE TITLE
How to connect to sqlsrv secondary database connection i used in laravel

### ISSUE THREAD

**Issue by cybershivanka** [reportico-web/laravel-reportico#10]
How to connect to sqlsrv secondary database connection i used in laravel.
i can connect to the default connection in database.php, but i need to connect sqlsrv as i'm using to extract data from my production database which is mssql.

**Comment by reportico-web** [comment]
Ok you can create a project and drop down the Database Type and select MsSQL sqlsrv option .. then put in your credentials. If you've got the pdo driver installed it should work. But let me know as it can be tricky connecting to sqlserver sometimes. But we can debug the connection string to get it working, if not

**Comment by cybershivanka** [comment]
this error comes up when configured as you said.
**_"Error: Project defined to use existing connection but none set."_**
please note i'm using laravel-reportico within laravel and reportico is working with "Existing Laravel Connection" fine.
thing is i'm using multiple database connections within laravel as my front end with login and all works with mysql database where sqlsrv connection is using for extract data for reporting from production database.

in database.php;

**'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'homestead'),
            'username' => env('DB_USERNAME', 'homestead'),
            'password' => env('DB_PASSWORD', 'secret'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => env('DB_HOST', '192.168.0.182'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'VDineBarista'),
            'username' => env('DB_USERNAME', 'sa'),
            'password' => env('DB_PASSWORD', 'omak@123'),
            'charset' => 'utf8',
            'prefix' => '',
            //'pooling'  => false,
        ],**

**Comment by cybershivanka** [comment]
Don't we have a option to select which connection from Existing Laravel Connection to be used in reportico?
where do i find the database connection settings ? please help as i need this done ASAP.

**Comment by cybershivanka** [comment]
ok, got it!
i found a small issue in adodb.inc.php file under reportico_adodb.
now its working all mssql queries, i had to configure the connection using MSSQL (with SQL SRV PDO..) as Database type.

Then i made the following code segments modified in adodb.inc.php:
	function __construct($queryID) 
	{
		$this->_queryID = $queryID;
	}

		function __construct($fakeid=1)
		{
		global $ADODB_FETCH_MODE,$ADODB_COMPAT_FETCH;
			// fetch() on EOF does not delete $this->fields
			$this->compat = !empty($ADODB_COMPAT_FETCH);
                        $parent::__construct($fakeid); // fake queryID
			$this->fetchMode = $ADODB_FETCH_MODE;
		}

My fixations were as follows, note, i haven't commented the entire code segment and only changed the required sections. so i added a new function as below;

	function ADORecordSet($queryID) 
	{
		$this->_queryID = $queryID;
	}	

then adjusted the erroneous code segment according to the new function as below;

		function __construct($fakeid=1)
		{
		global $ADODB_FETCH_MODE,$ADODB_COMPAT_FETCH;
			// fetch() on EOF does not delete $this->fields
			$this->compat = !empty($ADODB_COMPAT_FETCH);
                        $this->ADORecordSet($fakeid); // fake queryID
			$this->fetchMode = $ADODB_FETCH_MODE;
		}

please refer the url of entire code segment for the adodb.inc.php where i found the root cause.
[http://equimat.net/dolibarr/build/html/db/da7/adodb_8inc_8php_source.html](url)

**Comment by reportico-web** [comment]
Hmm thats strange, but im glad it worked. 

BTW what version of PHP are you using because later versions norally require that  __contruct to be set?

.. i will take on board your point about allowing you to select from the configured laravel projects

**Comment by cybershivanka** [comment]
yes it is strange, i'm using php. 5.6 at the moment, but same problem was occured when trying out with php 7. Anyway i'm glad it is working.

**Comment by reportico-web** [comment]
Cool :-)
