### ISSUE TITLE
Error on website

### ISSUE THREAD

**Issue by moncada1991** [reportico-web/laravel-reportico#15]
I was trying to see the example at http://www.reportico.org/laravel/public/index.php but is not longer working.

**Comment by reportico-web** [comment]
Thanks ive been upgradiing the site but havent got the laravel demo working... ill get this up in a few days and let you know here

**Comment by reportico-web** [comment]
Hi there .. ive got it going again ( except PDF output which im fixing up in next couple of days ).
Let me know if you need any help.. you can join the forum :)

http://www.reportico.org/forum

Also if you want to be one of the first to try the new 6.0.0 beta of the module you can use

follow the installtion instructions but use
```
composer require reportico/laravel-reportico  "^6.0"
```
