### ISSUE TITLE
Smarty error

### ISSUE THREAD

**Issue by dodyagung** [reportico-web/laravel-reportico#8]
Got 502 bad gateway on my nginx. Please help thanks.

2017/01/08 23:23:16 [error] 221#0: *597 FastCGI sent in stderr: "PHP message: PHP Warning:  Smarty error: unable to read resource: "admin.tpl" in /Users/dody/Documents/apps/valet/upg/vendor/reportico/laravel-reportico/src/Reportico/Reportico/smarty/libs/Smarty.class.php on line 1095" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /reportico HTTP/1.1", upstream: "fastcgi://unix:/Users/dody/.valet/valet.sock:", host: "upg.dev"
2017/01/08 23:23:16 [error] 221#0: *597 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /reportico HTTP/1.1", upstream: "fastcgi://unix:/Users/dody/.valet/valet.sock:", host: "upg.dev"

**Comment by reportico-web** [comment]
Hi there ... 


can you do 2 things ...

firstly edit the file: 
vendor/reportico/laravel-reportico/src/Reportico/Reportico/reportico.php around line 2963

Change

`    function initialize_panels($mode)
    {
        global $g_project;
        global $g_dropdown_menu;

        $smarty = new smarty();
        $smarty->template_dir = find_best_location_in_include_path( "templates" );
`

change to echo the smarty template dir....
`    function initialize_panels($mode)
    {
        global $g_project;
        global $g_dropdown_menu;

        $smarty = new smarty();
        $smarty->template_dir = find_best_location_in_include_path( "templates" );
echo "template folder  $smarty->template_dir";
die;
`

Can you tell me what this says...

then secondly a potential fix  is to do following. edit swutil.php in the same folder and got to line 1014 and change

`function find_best_location_in_include_path( $path )
{
    $newpath = $path;

    $reltoinclude;
    if ( substr($newpath, 0, 1) == "/" || substr($newpath, 0, 1) == "\\" )
    {
        if ( is_file ( $newpath ) || is_dir ( $newpath ) )
            return $newpath;
        else
            return false;
    }
`
to include an extra function call 

`function find_best_location_in_include_path( $path )
{
    $newpath = $path;
    if ( find_file_to_include($newpath, $newpath) )
        return $newpath;

    $reltoinclude;
    if ( substr($newpath, 0, 1) == "/" || substr($newpath, 0, 1) == "\\" )
    {
        if ( is_file ( $newpath ) || is_dir ( $newpath ) )
            return $newpath;
        else
            return false;
    }
`

Please let me know if this works.
